server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/forum?characterEncoding=utf-8&useSSL=false&serverTimezone=CST
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  thymeleaf:
    cache: true
  mail:
    host: smtp.sina.com
    port: 465
    username: kwh361@sina.com
    password: 3abdc653257298f3
    protocol: smtps
    properties.mail.smtp.ssl.enable: true
  redis:
    database: 1
    host: 106.53.96.171
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: forum-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  data:
    elasticsearch:
      cluster-name: kwin-forum
      cluster-nodes: 127.0.0.1:9300
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    scheduling:
      pool:
        size: 5
  quartz:
    job-store-type: jdbc
    scheduler-name: forumScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

logging:
  config: classpath:log4j2-dev.xml

forum:
  path:
    domain: http://localhost:8080
    upload: C:/developer_tools/workspace/workspace_forum/upload

qiniu:
  key:
    access: a9wT_6CuCET1TEsfmtiZsKWfh9EwOFJGYfp7UD09
    secret: gdxVKpMixZDjy8mGMnFsitd3QyePbyE_zbW7jKe-
  bucket:
    header:
      name: header2020
      url: http://qm2utoxy4.hn-bkt.clouddn.com

caffeine:
  posts:
    max-size: 15
    expire-seconds: 180

# actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
        exclude: info,caches